# Generated by Django 6.1.1 on 2026-09-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('elo', models.IntegerField(null=True)),
                ('image', models.TextField(null=True)),
                ('chess_profile', models.URLField(null=True)),
            ],
        ),
    ]
